IU.Plan.Web/Controllers/CalendarController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using IU.Plan.Web.Models;
using IU.Plan.Web.NH;
using IU.PlanManager.ConApp;
using IU.PlanManager.ConApp.Models;
using IU.PlanManager.Extensions;

namespace IU.Plan.Web.Controllers
{
    [Authorize]
    public class CalendarController : Controller
    {
        private IStore<Event> eventStore = new EventDBStore<Event>();

        private IStore<Activity> activityStore = new EventDBStore<Activity>();

        // GET: Calendar
        public ActionResult Index(DateTime yearMonthDay)
        {
            var today = DateTime.Today;

            var startMonth = yearMonthDay;
            var endMonth = startMonth.AddMonths(1);

            var events = eventStore.Entities.Where(evt =>
                   evt.StartDate >= startMonth && evt.StartDate < endMonth
                ).ToList();

            var model = new CalendarViewModel
            {
                Events = events,
                Limit = DateTime.DaysInMonth(yearMonthDay.Year, yearMonthDay.Month),
                ColCount = 7,
                StartDay = startMonth
            };

            return View(model);
        }
    }
}

IU.Plan.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Планировщик - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Планировщик", "Index", "Calendar", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li id="notify_today"><a>Сегодня <span class="badge"></span></a></li>
                    <li id="notify"><a>Завтра <span class="badge"></span></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Планировщик</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    @Scripts.Render("~/Scripts/site.js")

    <script type="text/javascript">
        $(document).ready(function () {
            setInterval(function () {
                checkEvents('?isToday=true', 'notify_today');
                checkEvents('', 'notify');
            }, 60 * 1000);
        });
    </script>
</body>
</html>